#!/usr/bin/env bash
set -x -eu -o pipefail
export OPENCONNECT_SERVER='https://cloudvpn.cms.gov/'
export HOST_CONFIG="--add-host=www.cedarimpl.cms.gov:10.138.78.45 \
--add-host=aris.cedarimpl.cms.gov:10.138.78.45 \
--add-host=alfabet.cedarimpl.cms.gov:10.138.78.45 \
--add-host=webmethods-apigw.cedarimpl.cms.gov:10.138.78.45 \
--add-host=webmethods-apiportal.cedarimpl.cms.gov:10.138.78.45"
./run
