version: 2
jobs:
  pre-test:
    docker:
      - image: &circleci trussworks/circleci:6986bb9022e5a83599feb66a7128a2d0fa12732a
    steps:
      - checkout

      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit

  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: ./build


workflows:
  version: 2
  validate:
    jobs:
      - pre-test
      - build
